### ISSUE TITLE
请问如何设置全文输出

### ISSUE THREAD

**Issue by Dover715** [feeddd/feeds#114]
请问如何设置全文输出

**Comment by Daymond** [comment]
同问，如何设置全文输出？

**Comment by mjysci** [comment]
Full-Text RSS，这里有篇[教程](https://blog.mjyai.com/2020/03/23/ubuntu-full-text-rss/)。  
不过我感觉用的人多了会受限导致抓取失败，所以建议去改进hamibot的[脚本](https://hamibot.com/marketplace/vLSBc)实现全文输出功能。

**Comment by feeddd** [comment]
feeddd 本身不支持全文，不考虑支持，因为这会有损创作者的权益
