### ISSUE TITLE
薅羊毛也得有个限度吧

### ISSUE THREAD

**Issue by pujx233** [feeddd/feeds#99]
注册github以来所有提交都是关于微信号转RSS的内容

上一个 wechat-feeds 几个月提交了上千个微信号，这次的项目几天时间又提交了上百次

你rss订阅微信号的需求那么大，能不能麻烦去选择付费？一个人订阅上千个公众号自己看得完吗？

别人开源给大家谋福利的项目不是这么薅羊毛的！

@testsetestset

**Comment by labulakalia** [comment]
改名了 @Angynond 真是个智障
